export const ONBOARDING_POTENTIAL_POLL_INTERVAL_MS = 3_000;
export const ONBOARDING_POTENTIAL_MAX_WAIT_MS = 600_000;
export const ONBOARDING_POTENTIAL_DISPLAY_MAX_WAIT_MS = 180_000;
export const ONBOARDING_POTENTIAL_MAX_CONSECUTIVE_POLL_ERRORS = 10;
export const ONBOARDING_POTENTIAL_JOB_RETRY_LIMIT = 1;
